default: &default
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  password: <%= ENV.fetch('REDIS_PASSWORD', nil).presence %>
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
  channel_prefix: <%= "chatwoot_#{Rails.env}_action_cable"  %>

development:
  <<: *default

test:
  adapter: test
  channel_prefix: <%= "chatwoot_#{Rails.env}_action_cable"  %>

staging:
  <<: *default

production:
  <<: *default
